# Generated by Django 3.2.7 on 2023-01-15 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=95)),
                ('body', models.TextField(blank=True, max_length=850, null=True)),
                ('image1', models.CharField(blank=True, max_length=800, null=True)),
                ('image2', models.CharField(blank=True, max_length=800, null=True)),
                ('image3', models.CharField(blank=True, max_length=800, null=True)),
                ('image4', models.CharField(blank=True, max_length=800, null=True)),
                ('image5', models.CharField(blank=True, max_length=800, null=True)),
                ('username', models.TextField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('post_type', models.TextField(blank=True, max_length=95, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.TextField(blank=True, max_length=95, null=True)),
                ('image1', models.CharField(blank=True, max_length=800, null=True)),
                ('image2', models.CharField(blank=True, max_length=800, null=True)),
                ('image3', models.CharField(blank=True, max_length=800, null=True)),
                ('image4', models.CharField(blank=True, max_length=800, null=True)),
                ('image5', models.CharField(blank=True, max_length=801, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=1)),
                ('caption', models.TextField(max_length=95)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hide_likes', models.BooleanField(default=True)),
                ('privacy', models.BooleanField(default=False)),
                ('username', models.TextField(blank=True, max_length=40, null=True)),
                ('text_content', models.TextField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.CharField(default='https://static.vecteezy.com/system/resources/thumbnails/005/544/718/small/profile-icon-design-free-vector.jpg', max_length=800)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
