# Generated by Django 3.2.7 on 2023-01-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag1',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag2',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
