# Generated by Django 3.2.7 on 2023-01-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectify', '0002_auto_20230115_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tag2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
