# Generated by Django 3.2.7 on 2023-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectify', '0007_auto_20230126_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='comments_amount',
            field=models.IntegerField(default=0),
        ),
    ]
