# Generated by Django 4.1.4 on 2023-02-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectify', '0008_auto_20230131_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
